server.port=8086
spring.application.name=consumer
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=pass

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nauvalhilmii21@gmail.com
spring.mail.password=wvbmgisdtovxjlyc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}